addons:
  apt:
    packages:
      - libsystemd-daemon-dev
      - libsystemd-id128-dev
      - libsystemd-journal-dev
      - libsystemd-login-dev

language:
  python

python:
  3.6

install:
  - "pip3 install coveralls"
  - "pip3 install -r requirements.txt"
  - "pip3 install -r dev-requirements.txt"

script:
  coverage run --source=archmap setup.py test

after_success:
  coveralls
