language:
  python

python:
  3.6

install:
  - "pip3 install coveralls"
  - "pip3 install -r requirements.txt"

script:
  coverage run --source=archmap setup.py test

after_success:
  coveralls --rcfile=.travis-coveragerc
